### ISSUE TITLE
massive recursion bug after reordering task

### ISSUE THREAD

**Issue by deiiviidas** [flathub/io.github.alainm23.planify#12]
(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.502: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.502: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.502: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.502: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.502: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.523: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.532: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.552: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.561: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.561: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.562: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.562: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.562: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.562: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.562: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.581: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.592: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.613: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.622: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.641: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.651: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.672: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.683: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.703: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.716: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.733: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.745: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.765: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.775: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.796: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.809: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.827: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.839: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.856: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:15:42.857: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed

**Comment by alainm23** [comment]
Thanks for reporting, this is only the deployment repository, please, if the error still persists, create it here.

https://github.com/alainm23/planify/issues
